/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dice.glb --transform 
Files: dice.glb [744.73KB] > /Users/joey/Documents/Projects/vite-react-boilerplate-main/src/_game/modals/dice-transformed.glb [41.22KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
	const { nodes, materials } = useGLTF("/dice-transformed.glb");
	const { isScoringNumber } = props;

	const diceMaterials = materials.Dice.clone();
	// if isScoringNumber is true, then we need to change the material of the dice to the scoring material
	if (isScoringNumber) {
		// green
		diceMaterials.color = new THREE.Color(0, 1, 0);
	}

	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Cube_1.geometry} material={materials.Dot} />
			<mesh
				geometry={nodes.Cube_2.geometry}
				material={isScoringNumber ? diceMaterials : materials.Dice}
			/>
			<mesh geometry={nodes.Cube_3.geometry} material={materials["Red Dot"]} />
		</group>
	);
}

//useGLTF.preload("/dice-transformed.glb");
